openapi: 3.0.1
info:
  title: Book Recommendation Plugin
  description: A plugin that allows the user to get a book recommendation based on a genre, author, or book title.
  version: 'v1'
servers:
  - url: http://localhost:3000
paths:
  /getGenre:
    post:
      operationId: getGenre
      summary: Get genre of a book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookTitle'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Genre'
components:
  schemas:
    BookGenre:
      type: object
      properties:
        genre:
          type: string
      required:
        - genre
    Book:
      type: object
      properties:
        title:
          type: string
        author:
          type: string
      required:
        - title
        - author
